# GitHub repo details
owner: rjkumar081
repo: cinepolis-status

# Websites to monitor
sites:
  - name: Cinepolis India
    url: https://www.cinepolis.com/in

# Status website configuration
status-website:
  # GitHub Pages (no custom domain)
  baseUrl: /cinepolis-status

  name: Cinepolis Status Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  
  introTitle: "Cinepolis Website Uptime Monitor"
  introMessage: >
    This dashboard shows the real-time uptime and response status of 
    **https://www.cinepolis.com/in**.  
    All checks run automatically every 5 minutes using GitHub Actions.
  
  navbar:
    - title: Status
      href: /
    - title: GitHub Repo
      href: https://github.com/rjkumar081/cinepolis-status
