owner: rjkumar081
deploy:
  branch: gh-pages
  folder: "public"
checks:
  - id: cinepolis
    name: Cinepolis India Website
    url: "https://www.cinepolis.com/in"
    method: GET
    expectedStatusCodes:
      - 200
notifications:
  commits: true
  status: true
status-website:
  cname: cinepolis-status
  logoUrl: ""
  favicon: ""
  baseUrl: "https://rjkumar081.github.io/cinepolis-status"
  navbar:
    - name: Home
      url: /
    - name: Status
      url: /status
  theme: dark
