# Change these first
owner: Raj-IT          # <-- आपका GitHub username
repo: cinepolis-status # <-- आपकी repository का नाम

sites:
  - name: Cinepolis India Website
    url: https://www.cinepolis.com/in

status-website:
  # यदि आप custom domain नहीं यूज़ कर रहे हैं तो CNAME हटाना जरूरी है
  # cname: demo.upptime.js.org

  # GitHub Pages के लिए baseUrl enable
  baseUrl: /cinepolis-status

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Cinepolis Website Status
  introTitle: "Cinepolis Website Status & Uptime Monitor"
  introMessage: >
    This status page automatically monitors **https://www.cinepolis.com/in**
    every 5 minutes and shows real-time uptime, response timestamps,
    and incident history. Powered by GitHub Actions and Upptime.

  navbar:
    - title: Status
      href: /
    - title: GitHub Repo
      href: https://github.com/Raj-IT/cinepolis-status
